version: '3'
services:
  backend:
    image:  "oscarygutierrezg/test-tul-backend"
    ports:
      - "8081:8080"
    networks:
      - shared-net
  frontend:
    image: "oscarygutierrezg/test-tul-frontend"
    ports:
      - "8090:80"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - shared-net
networks:
  shared-net:
    driver: bridge
