version: '3'

services:
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - shared-net
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
    networks:
      - shared-net
  backend:
    image: backend
    ports:
      - "8081:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - shared-net
  frontend:
    image: frontend
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - shared-net
networks:
  shared-net:
    driver: bridge